[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "cd server && npm install",
  "cd server && npx prisma generate",
  "cd server && npx prisma migrate deploy"
]

[start]
cmd = "cd server && node index.js"
