{
  "phases": {
    "setup": {
      "nixPkgs": ["nodejs-18_x"]
    },
    "install": {
      "cmds": ["npm ci"]
    },
    "build": {
      "cmds": ["echo 'Build complete'"]
    },
    "start": {
      "cmd": "npm start"
    }
  }
}
